### ISSUE TITLE
Error de descàrrega de cartografia vectorial per Municipi

### ISSUE THREAD

**Issue by nilhos** [OpenICGC/QgisPlugin#17]
Bona tarda,

En intentar descarregar la topografia vectorial 1:1.000 o el Referencial Topogràfic Territorial amb “tipus de descàrrega” per “Municipi” em salta el següent error:

2024-04-17T18:56:34     WARNING    Traceback (most recent call last):
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\transport\http.py", line 63, in open
              return self.u2open(u2request)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\transport\http.py", line 119, in u2open
              return url.open(u2request, timeout=tm)
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 523, in open
              response = meth(req, response)
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 632, in http_response
              response = self.parent.error(
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 561, in error
              return self._call_chain(*args)
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 494, in _call_chain
              result = func(*args)
              File "C:\OSGeo4W\apps\Python39\lib\urllib\request.py", line 641, in http_error_default
              raise HTTPError(req.full_url, code, msg, hdrs, fp)
             urllib.error.HTTPError: HTTP Error 503: Service Unavailable
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py", line 194, in canvasReleaseEvent
              self.subscene(event.pos().x(), event.pos().y())
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py", line 215, in subscene
              self.callback(area)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py", line 1379, in 
              self.download_map_area(geo, data_type, min_side, max_download_area, min_px_side, max_px_area, gsd, time_code, download_operation_code, filename, limits))
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py", line 1463, in download_map_area
              found_dict_list = self.find_point_secure(center.x(), center.y(), download_epsg)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\openicgc.py", line 1774, in find_point_secure
              self.geofinder.get_icgc_geoencoder_client().set_options(timeout=timeout)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\geofinder3\geofinder.py", line 60, in get_icgc_geoencoder_client
              self.icgc_geoencoder_client = Client(url="https://eines.icgc.cat/geocodificador/soap/ws/wss_1.0?wsdl", wsse=wsse_security)#, timeout=3)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\client.py", line 111, in __init__
              self.wsdl = reader.open(url)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\reader.py", line 151, in open
              d = self.fn(url, self.options)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\wsdl.py", line 135, in __init__
              d = reader.open(url)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\reader.py", line 78, in open
              d = self.download(url)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\reader.py", line 94, in download
              fp = self.options.transport.open(Request(url))
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\transport\http.py", line 174, in open
              return HttpTransport.open(self, request)
              File "C:\Users/Usuari1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\OpenICGC\lib\suds\transport\http.py", line 65, in open
              raise TransportError(str(e), e.code, e.fp)
             suds.transport.TransportError: HTTP Error 503: Service Unavailable

Moltes gràcies per la vostre atenció.

Salutacions.

**Comment by icgcaadell** [comment]
Hola

Abans d'ahir vàrem tenir una caiguda puntual d'alguns dels serveis que proporciona l'Institut Cartogràfic i Geològic de Catalunya i utilitza el connector OpenICGC que provocava aquests errors. Ara ja hauria de tonar a funcionar amb normalitat.

Si segueixes tenint problemes fes-nos-ho saber

Salutacions

**Comment by nilhos** [comment]
Solucionat, gràcies!

**Comment by icgcaadell** [comment]
Perfecte! Disculpa les molèsties.

En qualsevol cas publicaré la versió 1.1.18 que protegirà les descàrregues de la caiguda del servei de geocodificació (el que troba les adreces i municipis per coordenades i al revés), així hauria de mostrar un error controlat.

Salutacions
