### ISSUE TITLE
error con plugin Open ICGC / classFactory

### ISSUE THREAD

**Issue by nicolasfonty** [OpenICGC/QgisPlugin#20]
Hola, me aparece este error cuando trato de instalar el plugin de Open ICGC ; trabajo con Mac OS Mojave 10.14.6 y por eso no puedo instalar la ultima version de Qgis

estas son mis versiones de QGIS y Python
Python version: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.8.1-Zanzibar Zanzibar, exported 

Alguien sabria que hacer ? @icgcaadell @jarnaldich @bolollo @ibesora @sfggeogis 
muchas gracias :)  nico

**Couldn't load plugin 'OpenICGC' due to an error when calling its classFactory() method** 

**### TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases** 
Traceback (most recent call last):
  File "/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/__init__.py", line 29, in classFactory
    from .openicgc import OpenICGC
  File "/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/openicgc.py", line 60, in 
    from .qlib3.photosearchselectiondialog.photosearchselectiondialog import PhotoSearchSelectionDialog
  File "/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/qlib3/photosearchselectiondialog/photosearchselectiondialog.py", line 23, in 
    from qtrangeslider import QRangeSlider # Source: https://pypi.org/project/QtRangeSlider/
  File "/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib/qtrangeslider/__init__.py", line 6, in 
    from ._labeled import (
  File "/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib/qtrangeslider/_labeled.py", line 4, in 
    from ._sliders import QDoubleRangeSlider, QDoubleSlider, QRangeSlider
  File "/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib/qtrangeslider/_sliders.py", line 1, in 
    from ._generic_range_slider import _GenericRangeSlider
  File "/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib/qtrangeslider/_generic_range_slider.py", line 3, in 
    from ._generic_slider import CC_SLIDER, SC_GROOVE, SC_HANDLE, SC_NONE, _GenericSlider
  File "/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib/qtrangeslider/_generic_slider.py", line 46, in 
    class _GenericSlider(QSlider, Generic[_T]):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Python version: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.8.1-Zanzibar Zanzibar, exported 

Python Path:
/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python
/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib
D:\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc
/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib
/Users/nico/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib

**Comment by icgcaadell** [comment]
Hola

Gracias por reportar el problema, vamos a intentar reproducirlo en equipos nuestros. 
De todas maneras en versiones inferiores a QGIS v3.10 se desactivan algunas opciones por no estar soportadas o dar problemas en QGIS antiguos.

Saludos

**Comment by icgcaadell** [comment]
Hola

He estado haciendo pruebas en windows con QGIS v3.8.1 y parece que funciona correctamente. No disponemos de ningún equipo con Mac OS Mojave así que no he conseguido reproducir el error. 

De todas maneras analizando el error parece ser que el problema se da en una librería externa que utilizamos (QtRangeSlider) y lo he "simulado" añadiendo código erróneo. He añadido una protección en el código del plugin de manera que si no se puede cargar esa librería se desactivarán las opciones que la usan (sin dar un error descontrolado). El problema es que se desactivará la búsqueda de fotogramas del ICGC.

Adjunto una versión 1.1.22 parcheada a ver si te funciona:
[OpenICGC-1.1.22-FixQtRangeSlider.zip](https://github.com/user-attachments/files/17844388/OpenICGC-1.1.22-FixQtRangeSlider.zip)

Si me confirmas que funciona pasaré los cambios a la nueva versió 1.1.23 que estamos a punto de publicar. Ya nos dirás

Saludos

Albert

**Comment by icgcaadell** [comment]
Hola

Entiendo que se te ha solucionado el problema. Cierro el tema por inactividad

Saludos
