### ISSUE TITLE
Error installing on macOS

### ISSUE THREAD

**Issue by Aimonius** [OpenICGC/QgisPlugin#4]
I got this error when try to install on Qgis 3.6 in macOS 10.13.6

`No se pudo cargar el complemento 'OpenICGC' debido a un error al llamar a su método classFactory() 

ModuleNotFoundError: No module named 'win32clipboard' 
Traceback (most recent call last):
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/__init__.py", line 29, in classFactory
    from .openicgc import OpenICGC
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/openicgc.py", line 48, in 
    import qlib3.base.pluginbase
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib/qlib3/base/pluginbase.py", line 43, in 
    from . import loginfodialog
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib/qlib3/base/loginfodialog.py", line 17, in 
    import win32clipboard as clipboard
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'win32clipboard'

Versión de Python: 3.7.2 (default, Jan 13 2019, 12:50:01) [Clang 10.0.0 (clang-1000.11.45.5)] 
Versión de QGIS: 3.6.0-Noosa Noosa, 58734527ab 

Ruta de Python:
/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python
/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.6.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.6.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.6.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.6.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.6.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.6.app/Contents/Resources/python
/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
D:\eclipse\plugins\org.python.pydev_6.2.0.201711281614\pysrc
/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib
.
/Volumes/xxxxxx/Users/xxxxxx/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/OpenICGC/lib`

**Comment by icgcaadell** [comment]
Hello, I have corrected the error (I have protected the use of windows libraries). I have been able to do tests on Ubuntu and everything works. I am waiting to have a Mac OS-X machine to do the final verification

**Comment by Aimonius** [comment]
If I can help on something let me know. Thanks!

**Comment by icgcaadell** [comment]
Finally I have managed to test the plugin in Mac OS X and I think I have solved all the problems.
I have fixed the win32 libraries issue and another problem reading the metadata.txt file (in OSX)
I hope everything works correctly!

Fix: Commit 89af05f8983ce2eaacfb8102ee0ce9b912044a22
